# Generated by Django 4.2.3 on 2023-10-07 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='habit_guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(blank=True, max_length=1000, null=True, unique=True, verbose_name='действие')),
                ('is_useful', models.BooleanField(default=False, verbose_name='признак полезной привычки')),
                ('is_nice', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('is_activ', models.BooleanField(default=True, verbose_name='признак активной привычки')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
        migrations.CreateModel(
            name='habit_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(default='', max_length=150, unique=True, verbose_name='место')),
                ('date_of_habit', models.DateTimeField(blank=True, null=True, verbose_name='время выполнения привычки')),
                ('periodicity', models.DurationField(blank=True, null=True, verbose_name='Периодичность')),
                ('reward', models.CharField(default='Благодарность', max_length=150, verbose_name='Вознаграждение')),
                ('time_to_complete', models.DurationField(blank=True, null=True, verbose_name='время на выполнение привычки')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичной привычки')),
                ('is_activ', models.BooleanField(default=True, verbose_name='признак активной привычки')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.habit_guide', to_field='action', verbose_name='действие')),
                ('associated_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_action', to='main.habit_guide', to_field='action', verbose_name='связанное действие')),
                ('email', models.ForeignKey(default='mail', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='почта_пользователя')),
            ],
            options={
                'verbose_name': 'Моя привычка',
                'verbose_name_plural': 'Мои привычки',
            },
        ),
    ]
