# Generated by Django 4.2.5 on 2023-10-08 11:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit_user',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_fk', to='main.habit_guide', to_field='action', verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='habit_user',
            name='associated_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_action_fk', to='main.habit_guide', to_field='action', verbose_name='связанное действие'),
        ),
        migrations.AlterField(
            model_name='habit_user',
            name='date_of_habit',
            field=models.DateTimeField(blank=True, default=datetime.date(2023, 10, 8), null=True, verbose_name='время выполнения привычки'),
        ),
        migrations.AlterField(
            model_name='habit_user',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='почта_пользователя'),
        ),
        migrations.AlterField(
            model_name='habit_user',
            name='periodicity',
            field=models.DurationField(default=datetime.timedelta(days=7), verbose_name='Периодичность'),
        ),
        migrations.AlterField(
            model_name='habit_user',
            name='place',
            field=models.CharField(default='Здесь и сейчас', max_length=150, unique=True, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='habit_user',
            name='reward',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Вознаграждение'),
        ),
        migrations.AlterField(
            model_name='habit_user',
            name='time_to_complete',
            field=models.DurationField(blank=True, default=120, null=True, verbose_name='время на выполнение привычки'),
        ),
    ]
