# Generated by Django 4.2.5 on 2023-10-08 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_habit_user_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit_user',
            name='place',
            field=models.CharField(default='Здесь и сейчас', max_length=150, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='habit_user',
            name='reward',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='Вознаграждение'),
        ),
        migrations.AlterField(
            model_name='habit_user',
            name='time_to_complete',
            field=models.DurationField(blank=True, default=datetime.timedelta(seconds=120), null=True, verbose_name='время на выполнение привычки'),
        ),
    ]
