# Generated by Django 4.2.5 on 2023-10-08 12:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_habit_user_place_alter_habit_user_reward_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit_user',
            name='date_of_habit',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='время выполнения привычки'),
        ),
    ]
