# Generated by Django 4.2.5 on 2023-10-08 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_habit_user_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit_user',
            name='owner',
        ),
    ]
