# Generated by Django 4.2.5 on 2023-10-08 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_remove_habit_user_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit_user',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='почта_пользователя'),
        ),
    ]
