# Generated by Django 4.2.5 on 2024-03-03 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_habit_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit_user',
            name='action',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.habit_guide', unique=True, verbose_name='действие'),
            preserve_default=False,
        ),
    ]
